plugins:
  - jekyll-sass-converter # Añade esto si usas SCSS

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

collections:
  categories:
    output: true
    permalink: /categorias/:path/
# Permite imágenes externas
whitelist:
  - https://m.media-amazon.com/
